@startuml
title Warmhouse System Сomponent Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container(apiGateway, "API Gateway", "HTTP API", "Принимает запросы пользователя и направляет их к микросервисам")
Container_Ext(sensorService, "Sensor Service", "Go", "Управление датчиками")
ContainerDb_Ext(temperatureDb, "Temperature DB", "PostgreSQL", "Хранит температурные показания")

Container_Boundary(temperatureService, "Temperature Monitoring Service", "Go") {
    ' принимает запросы к температурному сервису.
    Component(apiController, "API Controller", "HTTP API", "Внутренний компонент Temperature Monitoring Service. Принимает запросы внутри сервиса")
    ' основная логика: получить текущую температуру, сохранить новое показание.
    Component(ServiceLayer, "Service Layer", "Основная логика")
    ' для работы с базой данных
    Component(RepositoryLayer, "Repository Layer", "Компонент для работы с базой данных")
    ' просто ходит в другой сервис
    Component(SensorClient, "Sensor Client", "Запрашивает информацию о датчике")

}

Rel(apiGateway, apiController, "Запрашивает текущую температуру")
Rel(apiController, ServiceLayer, "Передаёт запрос")
Rel(ServiceLayer, RepositoryLayer, "Читает температурные показания")
Rel(RepositoryLayer, temperatureDb, "Читает данные")

Rel(ServiceLayer, SensorClient, "Проверяет информацию о датчике")
Rel(SensorClient, sensorService, "Запрашивает информацию о датчике")

@enduml

' обычной поток связей такой
' API Gateway -> API Controller -> Service Layer -> Repository -> Temperature DB
'                                       |
'                                       -> Sensor Client -> Sensor Service