@startuml
title Warmhouse system Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "Пользователь системы умного дома")
System(WarmhouseSystem, "Warnhouse system", "Монолитное приложение для управления отоплением и мониторинга температуры")

System_Ext(sensor, "Temperature Sensor", "Датчик температуры в доме")
System_Ext(heating, "Heating System", "Система отопления в доме пользователя")

SystemDb(postgres, "PostgreSQL", "База данных для хранения информации о датчиках, показаниях и состоянии системы")

Rel(user, WarmhouseSystem, "Просматривает температуру и управляет отоплением")
Rel(WarmhouseSystem, postgres, "Сохраняет и читает данные")
Rel(sensor, WarmhouseSystem, "Передаёт данные о температуре")
Rel(WarmhouseSystem, heating, "Отправляет команды включения и выключения отопления")

@enduml